### ISSUE TITLE
Create a README with basic information

### ISSUE THREAD

**Issue by evgeniya-egupova** [evgeniya-egupova/wise_host#4]
Main README should contain project description, explain to whom and for what purposes this tool is suitable. There should be template fields to describe how to run the demo/use the tool in the future. The README must end with the requirements specification.

**Comment by SalmanRashid1979** [comment]
Hi @evgeniya-egupova I am a professional technical writer looking to contribute to open source projects on GitHub. Is this something that I can help you with?

**Comment by olegov99** [comment]
@SalmanRashid1979 How much would it cost, sir?

**Comment by SalmanRashid1979** [comment]
@olegov99 Thanks for your reply. I am actually looking to learn GitHub and become a part of the community so I am happy to volunteer and not charge for my contribution. Looking forward to hearing from you soon. Thanks!
